// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igkvhbaedsqzkwavcwtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlna3ZoYmFlZHNxemt3YXZjd3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjk3ODMsImV4cCI6MjA2MDcwNTc4M30.t89z49OViHSxO7w3J5hkycQvtrs5YsrHb4iQ27Yuseo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);